doctrine:
    dbal:
        url: "%env(resolve:DATABASE_URL)%"

    orm:
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Feed:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/src/Domain/Feed/Entity"
                prefix: 'App\Domain\Feed\Entity'
                alias: Feed
            ItemStatus:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/src/Domain/ItemStatus/Entity"
                prefix: 'App\Domain\ItemStatus\Entity'
                alias: ItemStatus
            User:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/src/Domain/User/Entity"
                prefix: 'App\Domain\User\Entity'
                alias: User
            App:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/src/Entity"
                prefix: 'App\Entity'
                alias: App

when@prod:
    doctrine:
        orm:
            metadata_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool

    framework:
        cache:
            pools:
                doctrine.system_cache_pool:
                    adapter: cache.system
