framework:
    messenger:
        transports:
            sync: "sync://"

        routing:
            'App\Message\HeartbeatMessage': sync
            'App\Message\RefreshFeedsMessage': sync
            'App\Message\CleanupContentMessage': sync
