framework:
    messenger:
        buses:
            messenger.bus.default:
                middleware:
                    - App\Messenger\Middleware\ProcessedMessageMiddleware

        transports:
            sync: "sync://"

        routing:
            'App\Message\HeartbeatMessage': sync
            'App\Message\RefreshFeedsMessage': sync
            'App\Message\CleanupContentMessage': sync
