security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users\User
                property: email
        webhook_provider:
            memory:
                users:
                    webhook:
                        {
                            password: "%env(WEBHOOK_PASSWORD)%",
                            roles: ["ROLE_WEBHOOK"],
                        }

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        webhook:
            pattern: ^/webhook
            stateless: true
            provider: webhook_provider
            http_basic:
                realm: "Webhook"
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppAuthenticator
            entry_point: App\Security\AppAuthenticator
            logout:
                path: auth_logout
                target: auth_login

    access_control:
        - { path: ^/webhook, roles: ROLE_WEBHOOK }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/setup, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
