twig:
    file_name_pattern: "*.twig"
    paths:
        "%kernel.project_dir%/assets/icons": icons
    globals:
        app_timezone: "%env(APP_TIMEZONE)%"
    form_themes:
        - "form/theme.html.twig"

when@test:
    twig:
        strict_variables: true
