framework:
    profiler:
        enabled: "%env(bool:PROFILER_ENABLED)%"
        collect: "%env(bool:PROFILER_ENABLED)%"
        dsn: "file:%kernel.project_dir%/var/profiler"

web_profiler:
    toolbar:
        enabled: "%env(bool:PROFILER_ENABLED)%"
